# set PATH so it includes user's private path if it exists
function MaybeAddToPath {
    if [ -d "$1" ]; then
        PATH="$1:$PATH"
    fi
}
MaybeAddToPath $HOME/bin
MaybeAddToPath $HOME/local/bin
MaybeAddToPath $HOME/opt/sh-tool/bin
MaybeAddToPath $HOME/opt/asdk/platform-tools

unsetopt SHARE_HISTORY

# Editor settings.
EMACS=
EMACSCLIENT=
if [ "Darwin" = "$(uname)" ]; then
    EMACS=/Applications/Emacs.app/Contents/MacOS/Emacs
    EMACSCLIENT=/usr/local/bin/emacsclient
else
    EMACS=$(where emacs)
    EMACSCLIENT=$(where emacsclient)
fi
export ALTER_EDITOR="$EMACS -nw"
export EDITOR="$EMACSCLIENT"
alias emacs="$EMACS"
alias ec="$EMACSCLIENT -n"
alias ecnw="$EMACSCLIENT -nw"
